service: learning-cards-backend

provider:
  name: aws
  runtime: nodejs18.x
  region: ${self:custom.region}
  stage: ${self:custom.stage}
  deploymentBucket:
    name: sls-deploy-${opt:account, 'serverless'}-${self:provider.region}
    serverSideEncryption: AES256
  environment:
    LOG_LEVEL: ${file(config/${self:custom.stage}.json):logLevel}
    REGION: ${self:custom.region}
    COGNITO_USER_POOL_ID: ${self:custom.values.cognito.userPoolId}
    COGNITO_CLIENT_ID: ${self:custom.values.cognito.clientId}
    COGNITO_CLIENT_SECRET: ${self:custom.values.cognito.clientSecret}
    COGNITO_DOMAIN: ${self:custom.names.cognito.domain}
    ORIGIN: ${self:custom.values.origin}
    REDIRECT_URI: ${self:custom.values.redirectUrl}
    EMAILS_WHITE_LIST: ${self:custom.values.emailsWhiteList}
    # Used internally by aws-jwt-verify
    JWT_ISSUER: https://cognito-idp.${self:provider.region}.amazonaws.com/${self:provider.environment.COGNITO_USER_POOL_ID}

custom:
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'eu-central-1'}
  names:
    cognito:
      domain: learning-cards-${self:custom.stage}
  values:
    origin: ${file(config/${self:custom.stage}.json):origin}
    redirectUrl: ${self:custom.values.origin}/auth/callback
    emailsWhiteList: ${file(config/${self:custom.stage}.json):emailsWhiteList}
    cognito:
      userPoolName: learning-cards-userpool-${self:custom.stage}
      userPoolId: ${ssm:/app/cognito/user_pool_id}
      clientId: ${ssm:/app/cognito/client_id}
      clientSecret: ${ssm:/app/cognito/client_secret}
#      userPoolId: "CHANGE_AFTER_FIRST_DEPLOYMENT"
#      clientId: "CHANGE_AFTER_FIRST_DEPLOYMENT"
#      clientSecret: "CHANGE_AFTER_FIRST_DEPLOYMENT"
  authorizer:
    name: authorizer
    arn: !GetAtt AuthorizerLambdaFunction.Arn
    type: request
  cors:
    origin: ${self:custom.values.origin}
    headers:
      - Content-Type
      - Authorization
      - X-Amz-Date
      - X-Api-Key
      - X-Amz-Security-Token
      - Access-Control-Allow-Headers
      - Access-Control-Allow-Origin
      - X-Requested-With
    allowCredentials: true

functions:
  token:
    handler: src/cognito/authentication.token
    events:
      - http:
          path: /auth/token
          method: post
          cors: ${self:custom.cors}

  authorizer:
    handler: src/cognito/authorizer.verify

  welcome:
    handler: src/handler.welcome
    events:
      - http:
          path: welcome
          method: get
          cors: ${self:custom.cors}
          authorizer: ${self:custom.authorizer}

  # Cognito Hooks
  preSignUp:
    handler: src/cognito/hooks.preSignUp
    events:
      - cognitoUserPool:
          pool: ${self:custom.values.cognito.userPoolName}
          trigger: PreSignUp
          existing: true

resources:
  - ${file(templates/cognito.yml)}

plugins:
  - serverless-plugin-typescript
  - serverless-deployment-bucket
  - serverless-plugin-common-excludes
  - serverless-plugin-include-dependencies
